# Sample .travis.yml for R projects +
# https://github.com/travis-ci/travis-ci/issues/5775

## bioc uses r-release from mid
## april to mid october: https://www.bioconductor.org/developers/how-to/useDevel/

## Broken now: https://travis-ci.community/t/r-bioc-devel-is-broken-bioconductor-version-3-11-requires-r-version-4-0/5745
language: r
r: bioc-devel


warnings_are_errors: true

sudo: required

cache: packages

r_github_packages:
  - r-lib/covr



#######  x22
install:
- Rscript -e 'install.packages("BiocManager"); BiocManager::install(version="devel", ask = FALSE); install.packages(c("devtools","testthat","roxygen2","Oncotree","rmarkdown","bookdown", "withr", "covr", "ggplot2", "ggrepel", "pander", "knitr")); BiocManager::install("BiocStyle", ask = FALSE); devtools::install_deps("OncoSimulR")'; devtools::install_github("r-lib/covr")'



before_script:
   - R CMD build --keep-empty-dirs OncoSimulR
script:
   - R CMD check OncoSimulR_*.tar.gz

after_success:
   - Rscript -e 'library(covr); options(covr.flags = c(CPPFLAGS = "-O3 -g --coverage", CXX1XFLAGS = "-O3 -g --coverage", CXXFLAGS = "-O3 -g --coverage", CFLAGS = "-O3 -g --coverage", LDFLAGS = "--coverage")); covr::codecov()'



notifications:
  email:
    on_success: change
    on_failure: change



## Remember to fix the file paths as:

## R/::OncoSimulR/R
## src/::OncoSimulR/src

##  so that codecov info is shown.



## Remember that OS X could be used instead of Linux.
## But it is instead of, not in addition to. See:
## "Linux or OS X builds" in https://github.com/craigcitro/r-travis





## Do I still need this?
# https://github.com/travis-ci/travis-ci/issues/6587
# Set CXX1X for R-devel, as R-devel does not detect CXX1X support for gcc 4.6.3,
# this was causing hunspell installation to fail
## before_install:
##   - if [[ "$TRAVIS_R_VERSION_STRING" = 'bioc-devel' ]]; then mkdir ~/.R && echo 'CXX1X=g++ -std=c++0x -g -O2 -fPIC' > ~/.R/Makevars; fi


## If we get

## Error in get0(oNam, envir = ns) : 

##   lazy-load database '/home/travis/R/Library/pkgbuild/R/pkgbuild.rdb' is corrupt

## try deleting the cache in travis:
## settings -> cache -> delete
## https://github.com/marinebon/p2p/issues/5#issuecomment-447877732